version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-ci-cd-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fr4tyns99wzv"
s3_prefix = "lambda-ci-cd-test"
region = "us-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
