on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-west-1
  STAGING_STACK_NAME: lambda-ci-cd-test-staging
  PROD_STACK_NAME: lambda-ci-cd-test-prod

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Run unit tests
        working-directory: tests/unit
        run: |
            pip install -r ../requirements.txt
            python -m pytest
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Build SAM app
        run: sam build --use-container
      - name: ZIP build files
        run: zip -r build.zip .aws-sam/build samconfig-staging.toml samconfig-dev.toml
      - name: Upload build artifacts to persistent storage
        uses: actions/upload-artifact@v2
        with:
          name: built-function
          path: build.zip
  # Note that AWS credentials can be set in the environment as well (e.g. separate staging and production AWS accounts)
  # TODO: Run integration tests
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    needs: build-test
    steps:
      - name: Download build artifacts from persistent storage
        uses: actions/download-artifact@v2
        with:
          name: built-function
      - name: Unzip build files
        run: unzip build.zip
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy to AWS staging environment
        run: sam deploy --config-file samconfig-staging.toml
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-staging
    steps:
      - name: Download build artifacts from persistent storage
        uses: actions/download-artifact@v2
        with:
          name: built-function
      - name: Unzip build files
        run: unzip build.zip
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy to AWS production environment
        run: sam deploy --config-file samconfig-prod.toml
