on:
  release:
    types: [published, deleted]
  workflow_dispatch:

env:
  AWS_REGION: us-west-1
  STAGING_STACK_NAME: lambda-ci-cd-test-staging
  PROD_STACK_NAME: lambda-ci-cd-test-prod

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Get latest release
        uses: dsaltares/fetch-gh-release-asset@0.0.7
        with:
          github_token: ${{ github.token }}
          file: build.zip
      - name: Unzip release files
        run: unzip build.zip
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy to AWS production environment
        run: sam deploy --config-file samconfig-prod.toml --no-fail-on-empty-changeset
