on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-west-1

jobs:
  # TODO: Separate setup, building, testing, and deployment steps into multiple jobs
  # The issue is that data is not persisted between jobs
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Build SAM app
        run: sam build --use-container
      - name: Run unit tests
        working-directory: tests/unit
        run: |
            pip install -r ../requirements.txt
            python -m pytest
      - name: Deploy to AWS
        run: sam deploy
